### ISSUE TITLE
Tutorial notebooks with Colab GPU: 'No Cuda GPUs are available'

### ISSUE THREAD

**Issue by foghlaimeoir** [adap/flower#1236]
### What is your question?

The tutorial Jupyter notebooks set the device as "cpu" by default and everything runs fine on Colab. After setting torch.device("cuda:0"), running the simulation gives 'RuntimeError: No CUDA GPUs are available' despite torch.cuda.is_available() being True in the notebook itself.

I am too much of a novice to make sense of the error message, I've tried downgrading ray from 1.12.0 down through 1.6.0 but the issue persists. I also tried referncing the GPU in the environment variable with 

%env CUDA_DEVICE_ORDER=PCI_BUS_ID
%env CUDA_VISIBLE_DEVICES=0

but that didn't work either.

This occurs in both the tutorial notebooks https://colab.research.google.com/github/adap/flower/blob/main/tutorials/Flower-1-Intro-to-FL-PyTorch.ipynb and https://colab.research.google.com/github/adap/flower/blob/main/tutorials/Flower-2-Strategies-in-FL-PyTorch.ipynb

Any advice on what else I can do? 

Starting the simulation giving the following error:

INFO flower 2022-05-27 22:02:05,875 | app.py:147 | Ray initialized with resources: {'node:172.28.0.2': 1.0, 'memory': 6233569691.0, 'CPU': 2.0, 'accelerator_type:P100': 1.0, 'object_store_memory': 3116784844.0, 'GPU': 1.0}
INFO flower 2022-05-27 22:02:05,878 | app.py:156 | Starting Flower simulation running: {'num_rounds': 5}
INFO flower 2022-05-27 22:02:05,887 | server.py:128 | Initializing global parameters
INFO flower 2022-05-27 22:02:05,892 | server.py:327 | Requesting initial parameters from one random client

---------------------------------------------------------------------------

RayTaskError(RuntimeError)                Traceback (most recent call last)

[<ipython-input-14-05d17298395b>](https://localhost:8080/#) in <module>()
     13     num_clients=NUM_CLIENTS,
     14     num_rounds=5,
---> 15     strategy=strategy,
     16 )

6 frames

[/usr/local/lib/python3.7/dist-packages/flwr/simulation/app.py](https://localhost:8080/#) in start_simulation(client_fn, num_clients, clients_ids, client_resources, num_rounds, strategy, ray_init_args)
    171         server=initialized_server,
    172         config=initialized_config,
--> 173         force_final_distributed_eval=False,
    174     )
    175 

[/usr/local/lib/python3.7/dist-packages/flwr/server/app.py](https://localhost:8080/#) in _fl(server, config, force_final_distributed_eval)
    146 ) -> History:
    147     # Fit model
--> 148     hist = server.fit(num_rounds=config["num_rounds"])
    149     log(INFO, "app_fit: losses_distributed %s", str(hist.losses_distributed))
    150     log(INFO, "app_fit: metrics_distributed %s", str(hist.metrics_distributed))

[/usr/local/lib/python3.7/dist-packages/flwr/server/server.py](https://localhost:8080/#) in fit(self, num_rounds)
    127         # Initialize parameters
    128         log(INFO, "Initializing global parameters")
--> 129         self.parameters = self._get_initial_parameters()
    130         log(INFO, "Evaluating initial parameters")
    131         res = self.strategy.evaluate(parameters=self.parameters)

[/usr/local/lib/python3.7/dist-packages/flwr/server/server.py](https://localhost:8080/#) in _get_initial_parameters(self)
    327         log(INFO, "Requesting initial parameters from one random client")
    328         random_client = self._client_manager.sample(1)[0]
--> 329         parameters_res = random_client.get_parameters()
    330         log(INFO, "Received initial parameters from one random client")
    331         return parameters_res.parameters

[/usr/local/lib/python3.7/dist-packages/flwr/simulation/ray_transport/ray_client_proxy.py](https://localhost:8080/#) in get_parameters(self)
     52             **self.resources
     53         ).remote(self.client_fn, self.cid)
---> 54         res = ray.worker.get(future_paramseters_res)
     55         return cast(
     56             common.ParametersRes,

[/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
     87             if func.__name__ != "init" or is_client_mode_enabled_by_default:
     88                 return getattr(ray, func.__name__)(*args, **kwargs)
---> 89         return func(*args, **kwargs)
     90 
     91     return wrapper

[/usr/local/lib/python3.7/dist-packages/ray/worker.py](https://localhost:8080/#) in get(object_refs, timeout)
   1619                     worker.core_worker.dump_object_store_memory_usage()
   1620                 if isinstance(value, RayTaskError):
-> 1621                     raise value.as_instanceof_cause()
   1622                 else:
   1623                     raise value

RayTaskError(RuntimeError): ray::launch_and_get_parameters() (pid=2844, ip=172.28.0.2)
  File "/usr/local/lib/python3.7/dist-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 99, in launch_and_get_parameters
    client: Client = _create_client(client_fn, cid)
  File "/usr/local/lib/python3.7/dist-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 123, in _create_client
    client: Union[Client, NumPyClient] = client_fn(cid)
  File "<ipython-input-13-96b32448ee50>", line 4, in client_fn
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by foghlaimeoir** [comment]
This was resolved by adding client_resources={"num_gpus": 1} as a parameter in start_simulation, to allow each virtual client to access the GPU.
